name: build mkdocs

on:
  push:
    branch:
      - "main"
  
jobs:
  build:
    name: build mkdocs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          
      - name: install lib
        run: |
          pip install mkdocs
          pip install mkdocs-material
          
      - name: Install SSH Client 🔑
        uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          
      - name: run mkdocs
        run: |
          cd docs
          mkdocs build
          
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          BASE_BRANCH: main
          BRANCH: gh-pages
          FOLDER: docs/site
          CLEAN: true
          SSH: true
